server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:stocks;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

# Scheduler config
sync:
  enabled: true
  cron: "0 */1 * * * *"  # every minute

# Vendor endpoints
vendorA:
  url: http://localhost:8080/mock/vendor-a/products

vendorB:
  csvPath: /tmp/vendor-b/stock.csv

# springdoc OpenAPI
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
